 build:
     command: gatsby build
     commandOrigin: config
     environment:
       - FAUNADB_SECRET_KEY
     functions: /opt/build/repo/functions
     publish: /opt/build/repo/public
   plugins:
     - inputs: {}
       origin: config
       package: '@netlify/plugin-functions-install-core'